name: CI
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry (pip)
        run: |
          python -m pip install --upgrade pip
          pip install poetry==1.8.3
          poetry --version

      - name: Install dependencies (main + dev) with extras
        run: |
          poetry install --with dev -E vector -E db
          poetry run python -c "import sys,platform; print('py', sys.version); print('plat', platform.platform())"

      - name: Lint (ruff)
        run: poetry run ruff check .

      - name: Format check (ruff)
        run: poetry run ruff format --check .

      - name: Type check (mypy)
        run: poetry run mypy src

      - name: Run tests
        run: poetry run pytest -q