name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix: { python-version: ["3.10","3.11","3.12"] }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: ${{ matrix.python-version }} }
      - uses: abatilo/actions-poetry@v3
        with: { poetry-version: "1.8.3" }
      - name: Install
        run: poetry install -E vector -E db
      - name: Lint & type-check
        run: |
          poetry run ruff check .
          poetry run ruff format --check .
          poetry run mypy src
      - name: Tests
        run: poetry run pytest -q
